### ISSUE TITLE
can not access to the backend

### ISSUE THREAD

**Issue by tshuy** [r-baker/simple-magento-vagrant#10]
I used your simple-magento-vagrant-master w/PHP5.4. I can see the Magento frontend by http://127.0.0.1.
But I can not access to the backend  http://127.0.0.1/admin using the username admin and password password123123.   Could you help me fix the problem?  I am using the Oracle VirtualBox 4.3.12r93733

**Comment by ravbetsky** [comment]
Yes, I've got the same issue again too, when trying to set up my dev environment on another computer. I suppose it might be associated with VirtualBox version.

P.S.
I've tried to solve this issue with this http://magento.stackexchange.com/questions/26071/magento-1-9-can-t-login-to-admin-panel but it didn't help.

**Comment by miguelcobain** [comment]
After a fresh install, I also can't login to the backend with the mentioned `admin` and `password123123` credentials.

**Comment by miguelcobain** [comment]
After an install on mac it worked. I'm confused.
