### ISSUE TITLE
webroot file/folder permissions

### ISSUE THREAD

**Issue by joh-klein** [r-baker/simple-magento-vagrant#19]
Has anybody else problems that the webroot is owned by vagrant:vagrant? Apache can't use the var folder and n98-magerun throws a long list of errors ...

**Comment by sadhasivam** [comment]
i am also getting  permission issue when i use  mount  with dmode=777 option change. vagrant/htdocs folder is having some permission issue because of that. 

further  n98-magerun execution permission "chmod +x .. " also not working.
