### ISSUE TITLE
Change folder sync method to rsync

### ISSUE THREAD

**Issue by joh-klein** [r-baker/simple-magento-vagrant#20]
It would speed up development and fix #19. Possible problems: it is not installed by default on windows. So we should maybe add it as an option?

**Comment by r-baker** [comment]
I tend to do this when I develop on Mac. The problem is it will break the install for Windows users. You can detect the environment in the Vagrantfile, so I guess we could wrap this in a condition.

**Comment by jhollender** [comment]
Would this speed up page load time when developing locally? I'm new to the whole Vagrant development approach.

**Comment by r-baker** [comment]
Yes it should do. Giving the VM a bit more memory can also help.

**Comment by joh-klein** [comment]
Changing to rsync was a massive speed improvement for me. I found it difficult, though, which folders to sync. Right now, I only sync the .modman folder, everything else is not directly accessible.

**Comment by jhollender** [comment]
What would I need to do to enable rsync?

**Comment by r-baker** [comment]
Not sure about rsync, but I use nfs for dev on Mac.

Add the following to the Vagrant file:

`config.vm.synced_folder ".", "/vagrant", type: "nfs"` then  `vagrant reload`

**Comment by joh-klein** [comment]
To get it to work, I changed the folder layout quite a bit. The problem with rsync for me is, that it destroys the symlinks from modman if you sync the complete "htdocs" directory. But since I mainly work in the .modman directory, I only sync that one and don't touch the other

  config.vm.synced_folder "./modman", "/var/www/html/.modman", 
    type: "rsync",
    rsync__exclude: ".git/",
    owner: "vagrant",
    group: "www-data"

**Comment by jhollender** [comment]
@r-baker if you specify NFS in the vagrantfile, do you have to make any changes to the bootstrap.sh file?
