### ISSUE TITLE
Perform apt-get update before installation

### ISSUE THREAD

**Issue by PhilippSchreiber** [r-baker/simple-magento-vagrant#24]
The mysql package has moved...

**Comment by r-baker** [comment]
Sorry, please could you elaborate?

Do you mean MySQL itself: https://github.com/r-baker/simple-magento-vagrant/blob/master/bootstrap.sh#l54

Or the PHP package: https://github.com/r-baker/simple-magento-vagrant/blob/master/bootstrap.sh#l12

**Comment by r-baker** [comment]
This is fixed in #21 :+1:

**Comment by PhilippSchreiber** [comment]
Great thanks!
