### ISSUE TITLE
Warning: Your Magento folder does not have sufficient write permissions.

### ISSUE THREAD

**Issue by andreacanton** [r-baker/simple-magento-vagrant#25]
In **Magento Connect Manager** this message appears and I can't install any extension with the tool.

    Warning: Your Magento folder does not have sufficient write permissions.

Am I the only one?

My system: Mac OSX Maverics - Vagrant 1.7.2 - VirtualBox 4.3.26 r98988. Commit ID "af200a9" with little modifications (sample_data to false,  user admin var, vm --memory to 2048)

**Comment by andreacanton** [comment]
every file in th e
-rw-rw-r-- 1 vagrant vagrant

**Comment by andreacanton** [comment]
sorry, my bad!

**Comment by corck** [comment]
I've the same problem

**Comment by steig** [comment]
I can't reproduce this with a fresh vagrant up.  Did this occur using when using magento connect?
