### ISSUE TITLE
Doesn't create admin user

### ISSUE THREAD

**Issue by andreacanton** [r-baker/simple-magento-vagrant#26]
after vagrant up I went to http://127.0.0.1:8080/admin and tried with "admin" "password123123" but gave me the "wrong login" error.
In the DB the "admin_user" table was empty.

Am I the only one to experience this?

I've bypassed the problem by following [this article](http://inchoo.net/magento/locked-out-from-magento-admin/)

My system: Mac OSX Maverics - Vagrant 1.7.2 - VirtualBox 4.3.26 r98988. Commit ID "af200a9" with little modifications (sample_data to false, user admin var, vm --memory to 2048)

**Comment by Galillei** [comment]
so i have this problem too. But when i run first  vagrant up its work ok, i can login, but after vagrant destroy - i can't be loggin in admin panel

**Comment by andreacanton** [comment]
Are you serious?
After `vagrant destroy` the machine is down and destroyed, so it's a normal behaviour.
Anyhow I suggest you to work after `vagrant up` and when you're done perform `vagrant halt`: that simply shoutdown your machine without destroying files and database with it.

Hope I help.
My problem occur right after the `vagrant up` process
