### ISSUE TITLE
Cannot make outbound HTTP Requests from vagrant VM

### ISSUE THREAD

**Issue by marblegravy** [r-baker/simple-magento-vagrant#28]
I had a lot of issues getting this to finish provisioning because of a problem with my VM being unable to resolve web addresses.

The fix for me was to modify the vagrantfile to:

`config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.name = "simple-magento-vagrant"
  end`

with the additional line to turn on the natdnshostresolver everything started working just fine!

Not sure if this is something that should be in your default config or whether it was an issue exclusive to my setup.

**Comment by rjbaker** [comment]
Thanks for the info :+1: I've not experienced this issue myself, but your fix is certainly useful for others who may encounter this.
