### ISSUE TITLE
Connecting via MySQL Workbench

### ISSUE THREAD

**Issue by joydasolive** [r-baker/simple-magento-vagrant#32]
How can I connect to the Magento DB via MySQL Workbench. I can SSH it and connect there. I can connect to other vagrant instances that I am running fine. But for this box, can't seem to find the right credentials. Any way to connect via TCP/IP and/or over SSH? Any help would be appreciated.

**Comment by annikaC** [comment]
I was able to connect via Standard TCP/IP over SSH via 127.0.0.1:2222
username: vagrant password: vagrant
Find your SSH key file in .vagrant/machines/default/virtualbox/private_key

MySQL Hostname: 127.0.0.1
MySQL Server Port: 3306
Username: magentouser
Password: password

Hope that helps!

**Comment by joydasolive** [comment]
Wow! Thanks Annika!
I was referring to the wrong private key. Thanks for pointing me to the right direction and save me from more hair pulling :)
I owe you one!

**Comment by rjbaker** [comment]
Thanks @annikaC :)

Alternatively you can add this line to the Vagrantfile:

`config.vm.network :forwarded_port, guest: 3306, host: 3306`.

Then run `vagrant reload`. This will allow you to connect without the SSH tunnel using only the username and pw.

**Comment by joydasolive** [comment]
Thanks Richard!

Why didn't I ask here before? :)

Thanks for the lib, mate. I never thought Magento install on my machine could be that simple. :)
