### ISSUE TITLE
Magento Sample Data Link outdated

### ISSUE THREAD

**Issue by ghost** [r-baker/simple-magento-vagrant#36]
Hi,

while reinstaling my magento environment I received this

--2015-11-24 22:59:20--  http://magento.com/downloads/assets/1.9.0.0/magento-sample-data-1.9.0.0.tar.gz
==> default: Resolving magento.com (magento.com)...
==> default: 66.211.190.110
==> default: Connecting to magento.com (magento.com)|66.211.190.110|:80...
==> default: connected.
==> default: HTTP request sent, awaiting response...
==> default: 404 Not Found

**Comment by ghost** [comment]
currently trying to find working wget link

**Comment by jasonchrin** [comment]
As a work around, I've downloaded the data and source files from Magento [directly](https://www.magentocommerce.com/download) and place them in your shared  httpdocs folder with the expected naming conventions.  

From there update your boostrap.sh file for the Mage and Data versions you've downloaded.  I've also commented out the lines that will download and clean up the files. (lines 72, 78, and 95)  It should still run fine then.

**Comment by carlos-reynosa** [comment]
I have the same issue.

**Comment by jay-saint** [comment]
I fixed this in my fork of this project pointing the links to https://github.com/Vinai/compressed-magento-sample-data 
[See my fix here](https://github.com/jay-saint/simple-magento-vagrant/commit/25f6b58b5b0bf7b9df54ce4673f65ca0d3f228ac?diff=unified) Line 106 and Line 110

**Comment by eucalyp** [comment]
you can find sample-data here: http://mirror.gunah.eu/magento/sample-data/
